#!/usr/bin/env sh
# -*- coding: utf-8 -*-

cd sonospy
echo python2.6 pycpoint.py $1 $2 $3 $4 $5 $6 $7 $8 > ../pycpoint.log
echo $! >../pycpoint.pid

cd ..
python2.6 web2py/web2py.py -L options.py >web2py.log &
echo $! >web2py.pid
